#!/usr/bin/python3

def print_matrix_integer(matrix=[[]]):
    for elem in matrix:
        mouchard = 0
        for number in elem:
            if mouchard > 1:
                print(" ", end='')
            mouchard += 2
            print ("{:d}".format(number), end='')
        print ()

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print_matrix_integer(matrix)
print("--")
print_matrix_integer()
